language: swift
osx_image: xcode10.1
branches:
 only:
   - master

before_install:
  - sudo brew install fastlane --no-rdoc --no-ri
install: true
script:
  - fastlane scan --scheme TAU --device "iPhone XR"
